In [2]:
import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
df = pd.read_csv("../data/cloudburst_dataset.csv")
df

,Cloud_Top_Height,Cloud_Base_Height,Optical_Thickness,Rainfall,Humidity,Temperature,Pressure,cloud_burst,source_type
0,14102.922471,4478.254022,81.458788,113.860000,98.456707,2.460000,831.976032,1,actual_based
1,16280.349921,3282.266452,100.754718,145.754353,96.215862,5.351109,806.439829,1,actual_based
2,14610.191174,3540.533728,79.712916,113.860000,100.342319,2.460000,832.275850,1,actual_based
3,14442.462510,5226.559823,68.037289,136.020961,98.155915,5.775977,847.044026,1,actual_based
4,15792.328643,2259.156281,65.791433,113.860000,100.163245,4.246368,847.358308,1,actual_based
...,...,...,...,...,...,...,...,...,...
9995,12416.550137,4418.751713,39.545973,158.989305,64.571139,33.088374,987.295359,0,normal_synthetic
9996,15214.536284,4427.930940,30.847472,138.896527,63.000000,13.006152,985.756576,1,normal_synthetic
9997,12942.719214,1080.787694,58.312846,137.858924,63.000000,30.256021,954.880262,1,normal_synthetic
9998,14245.382958,3919.624936,45.259220,116.310489,67.982034,23.534713,992.333455,0,normal_synthetic
9999,15378.079626,3163.485237,44.678716,113.860000,76.069197,3.945682,957.534119,0,normal_synthetic

In [4]:
X = df.drop(columns=["cloud_burst", "source_type"])
y = df["cloud_burst"]
X

,Cloud_Top_Height,Cloud_Base_Height,Optical_Thickness,Rainfall,Humidity,Temperature,Pressure
0,14102.922471,4478.254022,81.458788,113.860000,98.456707,2.460000,831.976032
1,16280.349921,3282.266452,100.754718,145.754353,96.215862,5.351109,806.439829
2,14610.191174,3540.533728,79.712916,113.860000,100.342319,2.460000,832.275850
3,14442.462510,5226.559823,68.037289,136.020961,98.155915,5.775977,847.044026
4,15792.328643,2259.156281,65.791433,113.860000,100.163245,4.246368,847.358308
...,...,...,...,...,...,...,...
9995,12416.550137,4418.751713,39.545973,158.989305,64.571139,33.088374,987.295359
9996,15214.536284,4427.930940,30.847472,138.896527,63.000000,13.006152,985.756576
9997,12942.719214,1080.787694,58.312846,137.858924,63.000000,30.256021,954.880262
9998,14245.382958,3919.624936,45.259220,116.310489,67.982034,23.534713,992.333455
9999,15378.079626,3163.485237,44.678716,113.860000,76.069197,3.945682,957.534119

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
model = LogisticRegression(max_iter=5000)

In [8]:
param_grid = {
    "C": np.logspace(-4, 4, 10),
    "penalty": ["l1", "l2", "elasticnet", None],
    "solver": ["liblinear", "saga"],
    "l1_ratio": [0, 0.5, 1]
}

In [9]:
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
    scoring="accuracy",
    verbose=2
)

grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 240 candidates, totalling 1200 fits

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .C=0.0001, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END .C=0.0001, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.7s
[CV] END .C=0.0001, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.7s
[CV] END .C=0.0001, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.6s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l1, solver=saga; total time=   0.4s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l2, solver=saga; total time=   0.5s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l2, solver=saga; total time=   2.7s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l2, solver=saga; total time=   2.7s
[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l2, solver=saga; total time=   2.7s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END C=0.0001, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END C=0.0001, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s

[CV] END C=0.0001, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END .C=0.0001, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ..C=0.0001, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ..C=0.0001, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END ..C=0.0001, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ..C=0.0001, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ..C=0.0001, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s

[CV] END ......C=0.0001, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.0001, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=1, penalty=None, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END ....C=0.0001, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s

[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END ......C=0.0001, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s

[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END .C=0.0001, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END C=0.000774263682681127, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s

[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.1s

[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s

[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.000774263682681127, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s

[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.005994842503189409, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s

[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s

[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s

[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s

[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.046415888336127774, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s

[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END C=2.782559402207126, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=0.3593813663804626, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s

[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s

[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=2.782559402207126, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.1s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=saga; total time=   0.1s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s

[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END C=21.54434690031882, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s

[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s

[CV] END C=21.54434690031882, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=21.54434690031882, l1_ratio=1, penalty=None, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.1s[CV] END C=166.81005372000558, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s

[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s

[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(

[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=saga; total time=   0.1s[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=saga; total time=   0.1s[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=166.81005372000558, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s[CV] END C=10000.0, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s[CV] END .....C=10000.0, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s[CV] END .....C=10000.0, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=10000.0, l1_ratio=0, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l2, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(

[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s[CV] END C=10000.0, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END .....C=10000.0, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.1s[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END C=1291.5496650148827, l1_ratio=1, penalty=l1, solver=saga; total time=   0.1s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=1291.5496650148827, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0, penalty=None, solver=saga; total time=   0.1s
[CV] END .....C=10000.0, l1_ratio=0, penalty=l1, solver=saga; total time=   0.1s
[CV] END .....C=10000.0, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END .C=10000.0, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s[CV] END C=10000.0, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s

[CV] END .....C=10000.0, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s[CV] END C=10000.0, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END C=10000.0, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0, penalty=None, solver=liblinear; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s

[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s[CV] END .....C=10000.0, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s

[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .C=10000.0, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s[CV] END .....C=10000.0, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s

[CV] END C=10000.0, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s[CV] END .C=10000.0, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=l2, solver=liblinear; total time=   0.0s

[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l1, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=None, solver=liblinear; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END .C=10000.0, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=1, penalty=elasticnet, solver=saga; total time=   0.1s
[CV] END ...C=10000.0, l1_ratio=0.5, penalty=l2, solver=saga; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=1, penalty=l2, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END .C=10000.0, l1_ratio=0.5, penalty=None, solver=saga; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END ...C=10000.0, l1_ratio=1, penalty=None, solver=saga; total time=   0.0s
[CV] END C=10000.0, l1_ratio=0.5, penalty=None, solver=liblinear; total time=   0.0s
[CV] END .....C=10000.0, l1_ratio=1, penalty=l1, solver=saga; total time=   0.0s

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l2)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=None)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1232: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:516: FitFailedWarning:
300 fits failed out of a total of 1200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
150 fits failed with the following error:
Traceback (most recent call last):
  File "/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 72, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
150 fits failed with the following error:
Traceback (most recent call last):
  File "/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 77, in _check_solver
    raise ValueError("penalty=None is not supported for the liblinear solver")
ValueError: penalty=None is not supported for the liblinear solver

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/model_selection/_search.py:1135: UserWarning: One or more of the test scores are non-finite: [0.46557143 0.53442857 0.81457143 0.82              nan 0.82
        nan 0.82528571 0.46557143 0.507      0.81457143 0.82
        nan 0.53442857        nan 0.82528571 0.46557143 0.53442857
 0.81457143 0.82              nan 0.52071429        nan 0.82528571
 0.80071429 0.78314286 0.81714286 0.82057143        nan 0.82057143
        nan 0.82528571 0.80071429 0.78314286 0.81714286 0.82057143
        nan 0.81742857        nan 0.82528571 0.80071429 0.78314286
 0.81714286 0.82057143        nan 0.78314286        nan 0.82528571
 0.81685714 0.82242857 0.82       0.82242857        nan 0.82242857
        nan 0.82528571 0.81685714 0.82242857 0.82       0.82242857
        nan 0.82228571        nan 0.82528571 0.81685714 0.82242857
 0.82       0.82242857        nan 0.82242857        nan 0.82528571
 0.82385714 0.825      0.82285714 0.82357143        nan 0.82357143
        nan 0.82528571 0.82385714 0.825      0.82285714 0.82357143
        nan 0.82471429        nan 0.82528571 0.82385714 0.825
 0.82285714 0.82357143        nan 0.825             nan 0.82528571
 0.82528571 0.82542857 0.82514286 0.82471429        nan 0.82471429
        nan 0.82528571 0.82528571 0.82528571 0.82514286 0.82471429
        nan 0.825             nan 0.82528571 0.82528571 0.82557143
 0.82514286 0.82471429        nan 0.82557143        nan 0.82528571
 0.82514286 0.82514286 0.82514286 0.82528571        nan 0.82528571
        nan 0.82528571 0.82514286 0.82514286 0.82514286 0.82528571
        nan 0.825             nan 0.82528571 0.82514286 0.82514286
 0.82514286 0.82528571        nan 0.82514286        nan 0.82528571
 0.82528571 0.82528571 0.82528571 0.82528571        nan 0.82528571
        nan 0.82528571 0.82528571 0.82528571 0.82528571 0.82528571
        nan 0.82528571        nan 0.82528571 0.82528571 0.82528571
 0.82528571 0.82528571        nan 0.82528571        nan 0.82542857
 0.82528571 0.82528571 0.82528571 0.82528571        nan 0.82528571
        nan 0.82528571 0.82528571 0.82528571 0.82528571 0.82528571
        nan 0.82528571        nan 0.82528571 0.82528571 0.82528571
 0.82528571 0.82542857        nan 0.82528571        nan 0.82528571
 0.82528571 0.82528571 0.82528571 0.82528571        nan 0.82528571
        nan 0.82528571 0.82528571 0.82528571 0.82528571 0.82528571
        nan 0.82528571        nan 0.82528571 0.82528571 0.82528571
 0.82528571 0.82528571        nan 0.82528571        nan 0.82528571
 0.82528571 0.82528571 0.82528571 0.82528571        nan 0.82528571
        nan 0.82542857 0.82528571 0.82528571 0.82528571 0.82528571
        nan 0.82528571        nan 0.82528571 0.82528571 0.82528571
 0.82528571 0.82528571        nan 0.82528571        nan 0.82528571]
  warnings.warn(
/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1221: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=5000), n_jobs=-1,
             param_grid={'C': array([1.00000000e-04, 7.74263683e-04, 5.99484250e-03, 4.64158883e-02,
       3.59381366e-01, 2.78255940e+00, 2.15443469e+01, 1.66810054e+02,
       1.29154967e+03, 1.00000000e+04]),
                         'l1_ratio': [0, 0.5, 1],
                         'penalty': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['liblinear', 'saga']},
             scoring='accuracy', verbose=2)

In [10]:
print("Best Parameters:", grid_search.best_params_)
print("Best CV Accuracy:", grid_search.best_score_)

Best Parameters: {'C': np.float64(0.3593813663804626), 'l1_ratio': 1, 'penalty': 'l1', 'solver': 'saga'}
Best CV Accuracy: 0.8255714285714285

In [11]:
best_model = grid_search.best_estimator_
print("Test Accuracy:", best_model.score(X_test, y_test))

Test Accuracy: 0.8236666666666667

In [12]:
joblib.dump(best_model, "../models/logistic_regression_model.pkl")

['../models/logistic_regression_model.pkl']

In [16]:
# Test Loaded Model
loaded_model = joblib.load("../models/logistic_regression_model.pkl")

# test_val = [[4000,16.16,82.50,1,78.4,26.5,935.81]] # Not CB
test_val = [[16000,21.35,3.33,583,78.1,25.8,935.86]] # CB

test_val = scaler.transform(test_val)
print("Test Value Prediction:", loaded_model.predict(test_val))
print("Test Value Prediction Probability:", loaded_model.predict_proba(test_val))

Test Value Prediction: [1]
Test Value Prediction Probability: [[0.00736468 0.99263532]]

/home/ilesh-dhall/cloud-burst-prediction/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(